[build]
command = ""
# Publish from the subfolder explicitly (no base)
publish = "Single_product_chatbot..py/."

[functions]
# Point to functions dir explicitly (no base)
directory = "Single_product_chatbot..py/netlify/functions"

# Include your Python core code so imports work on Netlify
included_files = [
  "Single_product_chatbot..py/Qna chatbot/**"
]
