[build]
command = ""
# Publish from the subfolder explicitly (no base)
publish = "Single_product_chatbot..py/."

[functions]
# Functions directory relative to repo root (no base)
directory = "Single_product_chatbot..py/netlify/functions"

# Bundle your Python core so imports work on Netlify
included_files = [
  "Single_product_chatbot..py/Qna chatbot/**"
]
