[build]
# Tell Netlify to build from the subfolder that contains your app
base = "Single_product_chatbot..py"
publish = "."
command = ""

[functions]
# This path is relative to the base directory above
directory = "netlify/functions"

# Include your Python core code in the function bundle
included_files = [
  "Single_product_chatbot..py/Qna chatbot/**"
]
