[build]
  # No static build in this backend-only setup; you can add a frontend later
  command = ""
  publish = "."

[functions]
  directory = "netlify/functions"
  # Include Python source outside the functions folder so it's available at runtime
  included_files = [
    "Qna chatbot/**"
  ]
  # ensure Python runtime (for Node functions only; harmless here)
  node_bundler = "esbuild"

# Optional: set function-level timeouts/memory if needed
#[[functions]]
#  name = "chat"
#  timeout = 26
#  memory = 1024
